#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : libmpack-lua
Version  : 1.0.10
Release  : 4
URL      : https://github.com/libmpack/libmpack-lua/archive/1.0.10/libmpack-lua-1.0.10.tar.gz
Source0  : https://github.com/libmpack/libmpack-lua/archive/1.0.10/libmpack-lua-1.0.10.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libmpack-lua-lib = %{version}-%{release}
Requires: libmpack-lua-license = %{version}-%{release}
BuildRequires : LuaJIT-dev
BuildRequires : libmpack-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
## libmpack lua binding
[![Travis Build Status](https://travis-ci.org/libmpack/libmpack-lua.svg?branch=master)](https://travis-ci.org/libmpack/libmpack-lua)

%package lib
Summary: lib components for the libmpack-lua package.
Group: Libraries
Requires: libmpack-lua-license = %{version}-%{release}

%description lib
lib components for the libmpack-lua package.


%package license
Summary: license components for the libmpack-lua package.
Group: Default

%description license
license components for the libmpack-lua package.


%prep
%setup -q -n libmpack-lua-1.0.10
cd %{_builddir}/libmpack-lua-1.0.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1680639592
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
make  %{?_smp_mflags}  USE_SYSTEM_LUA=yes USE_SYSTEM_MPACK=yes LUA_IMPL=luajit


%install
export SOURCE_DATE_EPOCH=1680639592
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libmpack-lua
cp %{_builddir}/libmpack-lua-%{version}/LICENSE-MIT %{buildroot}/usr/share/package-licenses/libmpack-lua/6a4d33353d2a8e515cb94ba0eac54ec4bfdabb50 || :
%make_install USE_SYSTEM_LUA=yes USE_SYSTEM_MPACK=yes LUA_IMPL=luajit

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/lua/5.1/mpack.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libmpack-lua/6a4d33353d2a8e515cb94ba0eac54ec4bfdabb50
